import {
  AlertCircle,
  Award,
  Badge,
  BanknoteArrowUp,
  BarChart,
  Bell,
  Bitcoin,
  Bolt,
  Book,
  Briefcase,
  Building,
  CalendarCheck,
  Captions,
  CheckCircle,
  ClipboardCheck,
  Code,
  Codepen,
  Coffee,
  CreditCard,
  File as DocumentIcon,
  Euro,
  Eye,
  File,
  FileQuestion,
  FileText,
  Flag,
  Ghost,
  Gift,
  Grid,
  Heart,
  HelpCircle,
  Kanban,
  Key,
  Landmark,
  Layout,
  LayoutGrid,
  LifeBuoy,
  MessageSquare,
  Monitor,
  Network,
  PackageCheckIcon,
  Users as PeopleIcon,
  Plug,
  RefreshCcw,
  RotateCcw,
  ScrollText,
  Settings,
  Share2,
  Shield,
  ShieldHalf,
  ShieldOff,
  ShieldUser,
  ShoppingCart,
  Split,
  SquareMousePointer,
  Star,
  Theater,
  ThumbsUp,
  TrendingUp,
  TriangleAlert,
  UserCheck,
  UserCircle,
  Users,
  Wallet,
  WalletCards,
  WebhookIcon,
  Briefcase as WorkIcon,
  Zap,
} from 'lucide-react';
import { type MenuConfig } from './types';

export const MENU_SIDEBAR: MenuConfig = [
  // { title: 'Dashboard', path: '/', icon: LayoutGrid, permission: 'tenant.dashboard.statistics' },
  { title: 'Analytics', path: '/payment-analytics', icon: BarChart },
  // { heading: 'Payments' },
  // { title: 'Transactions', path: '/transactions', icon: CreditCard, permission: 'tenant.payment.list' },
  // { title: 'Customers', path: '/customers', icon: Users, permission: 'tenant.customers.index' },
  // { title: 'Wallets', path: '/wallets', icon: Wallet, permission: 'tenant.businesses.wallets.list' },
  // { title: 'Settlement Banks', path: '/settlement-banks', icon: Landmark, permission: 'tenant.settlement-banks.index' },
  // { title: 'Withdrawals', path: '/withdrawals', icon: BanknoteArrowUp, permission: 'tenant.settlements.index' },
  // { title: 'Split Payment', path: '/transaction-splits', icon: Split, permission: 'tenant.split-groups.index' },
  // { title: 'Direct Debit', icon: PackageCheckIcon, disabled: true },
  // { title: 'Merchant Accounts', icon: Book, disabled: true },
  // { title: 'Disputes', icon: TriangleAlert, disabled: true },
  // { heading: 'Others' },
  // { title: 'WebHooks', path: '/webhooks', icon: WebhookIcon, permission: 'tenant.webhooks.index' },
  // { title: 'Compliance', path: '/compliance', icon: ClipboardCheck, permission: 'tenant.compliance.getComplianceDetails' },
  // { title: 'Team', icon: ShieldHalf, path: '/team', permission: 'tenant.rbac.roles.index' },
  // { title: 'Audit Trail', path: '/account/activity', icon: Eye, permission: 'tenant.audit-logs.index' },
  // { title: 'Settings', path: '/settings', icon: Settings, permission: 'tenant.settings.getProfile' },
  // { title: 'API Documentation', icon: DocumentIcon, path: 'https://docs.dotapay.ng' },
  // { title: 'Reversals', icon: RotateCcw, badge: 'Coming Soon', disabled: true },
];

export const MENU_SIDEBAR_CUSTOM: MenuConfig = [
  {
    title: 'Dashboards',
    icon: LayoutGrid,
    children: [
      { title: 'Light Sidebar', path: '/' },
      { title: 'Dark Sidebar', path: '/dark-sidebar' },
    ],
  },
  // { heading: 'Payments' },
  // { title: 'Transactions', path: '/transactions', icon: CreditCard, permission: 'tenant.payment.list' },
  // { title: 'Customers', path: '/customers', icon: Users, permission: 'tenant.customers.index' },
  // { title: 'Wallets', path: '/wallets', icon: Wallet, permission: 'tenant.businesses.wallets.list' },
  // { title: 'Settlement Banks', path: '/settlement-banks', icon: Landmark, permission: 'tenant.settlement-banks.index' },
  // { title: 'Withdrawals', path: '/withdrawals', icon: BanknoteArrowUp, permission: 'tenant.settlements.index' },
  // { title: 'Split Payment', path: '/transaction-splits', icon: Split, permission: 'tenant.split-groups.index' },
  // { title: 'Direct Debit', icon: PackageCheckIcon, disabled: true },
  // { title: 'Merchant Accounts', icon: Book, disabled: true },
  // { title: 'Disputes', icon: TriangleAlert, disabled: true },
  // { heading: 'Others' },
  // { title: 'WebHooks', path: '/webhooks', icon: WebhookIcon, permission: 'tenant.webhooks.index' },
  // { title: 'Compliance', path: '/compliance', icon: ClipboardCheck, permission: 'tenant.compliance.getComplianceDetails' },
  // { title: 'Team', icon: ShieldHalf, path: '/team', permission: 'tenant.rbac.roles.index' },
  // { title: 'Audit Trail', path: '/account/activity', icon: Eye, permission: 'tenant.audit-logs.index', },
  // { title: 'Settings', path: '/settings', icon: Settings, permission: 'tenant.settings.getProfile' },
  // { title: 'API Documentation', icon: DocumentIcon, path: 'https://docs.dotapay.ng' },
  // { title: 'Reversals', icon: RotateCcw, badge: 'Coming Soon', disabled: true },
];

export const MENU_SIDEBAR_COMPACT: MenuConfig = [
  {
    title: 'Dashboards',
    icon: LayoutGrid,
    children: [
      { title: 'Light Sidebar', path: '/' },
      { title: 'Dark Sidebar', path: '/dark-sidebar' },
    ],
  },
  // { heading: 'Payments' },
  // { title: 'Transactions', path: '/transactions', icon: CreditCard, permission: 'tenant.payment.list' },
  // { title: 'Customers', path: '/customers', icon: Users, permission: 'tenant.customers.index' },
  // { title: 'Wallets', path: '/wallets', icon: Wallet, permission: 'tenant.businesses.wallets.list' },
  // { title: 'Settlement Banks', path: '/settlement-banks', icon: Landmark, permission: 'tenant.settlement-banks.index' },
  // { title: 'Withdrawals', path: '/withdrawals', icon: BanknoteArrowUp, permission: 'tenant.settlements.index' },
  // { title: 'Split Payment', path: '/transaction-splits', icon: Split, permission: 'tenant.split-groups.index' },
  // { title: 'Direct Debit', icon: PackageCheckIcon, disabled: true },
  // { title: 'Merchant Accounts', icon: Book, disabled: true },
  // { title: 'Disputes', icon: TriangleAlert, disabled: true },
  // { heading: 'Others' },
  // { title: 'WebHooks', path: '/webhooks', icon: WebhookIcon, permission: 'tenant.webhooks.index' },
  // { title: 'Compliance', path: '/compliance', icon: ClipboardCheck, permission: 'tenant.compliance.getComplianceDetails' },
  // { title: 'Team', icon: ShieldHalf, path: '/team', permission: 'tenant.rbac.roles.index' },
  // { title: 'Audit Trail', path: '/account/activity', icon: Eye, permission: 'tenant.audit-logs.index', },
  // { title: 'Settings', path: '/settings', icon: Settings, permission: 'tenant.settings.getProfile' },
  // { title: 'API Documentation', icon: DocumentIcon, path: 'https://docs.dotapay.ng' },
  // { title: 'Reversals', icon: RotateCcw, badge: 'Coming Soon', disabled: true },
];

export const MENU_MEGA: MenuConfig = [
  {
    title: 'Dashboards',
    icon: LayoutGrid,
    children: [
      { title: 'Light Sidebar', path: '/' },
      { title: 'Dark Sidebar', path: '/dark-sidebar' },
    ],
  },
  // { heading: 'Payments' },
  // { title: 'Transactions', path: '/transactions', icon: CreditCard, permission: 'tenant.payment.list' },
  // { title: 'Customers', path: '/customers', icon: Users, permission: 'tenant.customers.index' },
  // { title: 'Wallets', path: '/wallets', icon: Wallet, permission: 'tenant.businesses.wallets.list' },
  // { title: 'Settlement Banks', path: '/settlement-banks', icon: Landmark, permission: 'tenant.settlement-banks.index' },
  // { title: 'Withdrawals', path: '/withdrawals', icon: BanknoteArrowUp, permission: 'tenant.settlements.index' },
  // { title: 'Split Payment', path: '/transaction-splits', icon: Split, permission: 'tenant.split-groups.index' },
  // { title: 'Direct Debit', icon: PackageCheckIcon, disabled: true },
  // { title: 'Merchant Accounts', icon: Book, disabled: true },
  // { title: 'Disputes', icon: TriangleAlert, disabled: true },
  // { heading: 'Others' },
  // { title: 'WebHooks', path: '/webhooks', icon: WebhookIcon, permission: 'tenant.webhooks.index' },
  // { title: 'Compliance', path: '/compliance', icon: ClipboardCheck, permission: 'tenant.compliance.getComplianceDetails' },
  // { title: 'Team', icon: ShieldHalf, path: '/team', permission: 'tenant.rbac.roles.index' },
  // { title: 'Audit Trail', path: '/account/activity', icon: Eye, permission: 'tenant.audit-logs.index', },
  // { title: 'Settings', path: '/settings', icon: Settings, permission: 'tenant.settings.getProfile' },
  // { title: 'API Documentation', icon: DocumentIcon, path: 'https://docs.dotapay.ng' },
  // { title: 'Reversals', icon: RotateCcw, badge: 'Coming Soon', disabled: true },
];

export const MENU_MEGA_MOBILE: MenuConfig = [
  {
    title: 'Dashboards',
    icon: LayoutGrid,
    children: [
      { title: 'Light Sidebar', path: '/' },
      { title: 'Dark Sidebar', path: '/dark-sidebar' },
    ],
  },
  // { heading: 'Payments' },
  // { title: 'Transactions', path: '/transactions', icon: CreditCard, permission: 'tenant.payment.list' },
  // { title: 'Customers', path: '/customers', icon: Users, permission: 'tenant.customers.index' },
  // { title: 'Wallets', path: '/wallets', icon: Wallet, permission: 'tenant.businesses.wallets.list' },
  // { title: 'Settlement Banks', path: '/settlement-banks', icon: Landmark, permission: 'tenant.settlement-banks.index' },
  // { title: 'Withdrawals', path: '/withdrawals', icon: BanknoteArrowUp, permission: 'tenant.settlements.index' },
  // { title: 'Split Payment', path: '/transaction-splits', icon: Split, permission: 'tenant.split-groups.index' },
  // { title: 'Direct Debit', icon: PackageCheckIcon, disabled: true },
  // { title: 'Merchant Accounts', icon: Book, disabled: true },
  // { title: 'Disputes', icon: TriangleAlert, disabled: true },
  // { heading: 'Others' },
  // { title: 'WebHooks', path: '/webhooks', icon: WebhookIcon, permission: 'tenant.webhooks.index' },
  // { title: 'Compliance', path: '/compliance', icon: ClipboardCheck, permission: 'tenant.compliance.getComplianceDetails' },
  // { title: 'Team', icon: ShieldHalf, path: '/team', permission: 'tenant.rbac.roles.index' },
  // { title: 'Audit Trail', path: '/account/activity', icon: Eye, permission: 'tenant.audit-logs.index', },
  // { title: 'Settings', path: '/settings', icon: Settings, permission: 'tenant.settings.getProfile' },
  // { title: 'API Documentation', icon: DocumentIcon, path: 'https://docs.dotapay.ng' },
  // { title: 'Reversals', icon: RotateCcw, badge: 'Coming Soon', disabled: true },
];

export const MENU_HELP: MenuConfig = [
  {
    title: 'Getting Started',
    icon: Coffee,
    path: 'https://keenthemes.com/metronic/tailwind/docs/getting-started/installation',
  },
  {
    title: 'Support Forum',
    icon: AlertCircle,
    children: [
      {
        title: 'All Questions',
        icon: FileQuestion,
        path: 'https://devs.keenthemes.com',
      },
      {
        title: 'Popular Questions',
        icon: Star,
        path: 'https://devs.keenthemes.com/popular',
      },
      {
        title: 'Ask Question',
        icon: HelpCircle,
        path: 'https://devs.keenthemes.com/question/create',
      },
    ],
  },
  {
    title: 'Licenses & FAQ',
    icon: Captions,
    path: 'https://keenthemes.com/metronic/tailwind/docs/getting-started/license',
  },
  {
    title: 'Documentation',
    icon: FileQuestion,
    path: 'https://keenthemes.com/metronic/tailwind/docs',
  },
  { separator: true },
  { title: 'Contact Us', icon: Share2, path: 'https://keenthemes.com/contact' },
];

export const MENU_ROOT: MenuConfig = [
  {
    title: 'Dashboards',
    icon: LayoutGrid,
    children: [
      { title: 'Light Sidebar', path: '/' },
      { title: 'Dark Sidebar', path: '/dark-sidebar' },
    ],
  },
  { heading: 'Payments' },
  { title: 'Transactions', path: '/transactions', icon: CreditCard },
  { title: 'Customers', path: '/customers', icon: Users },
  { title: 'Wallets', path: '/wallets', icon: Wallet },
  { title: 'Settlement Banks', path: '/settlement-banks', icon: Landmark },
  { title: 'Withdrawals', path: '/withdrawals', icon: BanknoteArrowUp },
  { title: 'Split Payment', path: '/transaction-splits', icon: Split },
  { title: 'Direct Debit', icon: PackageCheckIcon, disabled: true },
  { title: 'Merchant Accounts', icon: Book, disabled: true },
  { title: 'Disputes', icon: TriangleAlert, disabled: true },
  { heading: 'Others' },
  { title: 'WebHooks', path: '/webhooks', icon: WebhookIcon },
  { title: 'Compliance', path: '/compliance', icon: ClipboardCheck },
  { title: 'Team', icon: ShieldHalf, path: '/team' },
  { title: 'Audit Trail', path: '/account/activity', icon: Eye, },
  { title: 'Settings', path: '/settings', icon: Settings },
  { title: 'API Documentation', icon: DocumentIcon, path: 'https://docs.dotapay.ng' },
  { title: 'Reversals', icon: RotateCcw, badge: 'Coming Soon', disabled: true },
];
